<a href="https://colab.research.google.com/github/exxom/Pytorch-youtube/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

import numpy as np

# **LIST**

In [2]:
np_list=[[1,2,3,4],[5,6,7,8,9]]
np_list

[[1, 2, 3, 4], [5, 6, 7, 8, 9]]

# **NUMPY ARRAY**

In [3]:
np1=np.random.rand(3,4)
np1

array([[0.32340338, 0.16703575, 0.79823781, 0.66269129],
       [0.41643883, 0.75196882, 0.16900874, 0.66979274],
       [0.58896932, 0.33920331, 0.34329488, 0.86947532]])

In [4]:
np1.dtype

dtype('float64')

# **TENSORS**

In [7]:
tensor_2d=torch.randn(3,4)
tensor_2d

tensor([[ 1.1776, -0.1900,  0.1846, -0.8682],
        [ 1.1808, -0.2618,  0.7776, -0.2710],
        [-0.3149,  0.4007,  1.2609,  0.4119]])

In [8]:
tensor_3d = torch.zeros(2,3,4)
tensor_3d

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [9]:
my_tensor = torch.tensor(np1)
my_tensor

tensor([[0.3234, 0.1670, 0.7982, 0.6627],
        [0.4164, 0.7520, 0.1690, 0.6698],
        [0.5890, 0.3392, 0.3433, 0.8695]], dtype=torch.float64)